export const DASHBOARD = '/dashboard'
export const ASSETS = DASHBOARD + '/assets'
export const DELIVERIES = DASHBOARD + '/deliveries'
export const REPAIRS = DASHBOARD + '/repairs'
export const INVOICES = DASHBOARD + '/invoices'
export const SETTINGS = DASHBOARD + '/settings'

export const SIGNIN = '/signin'
export const SIGNUP = '/signup'
export const PASSWORD_FORGET = '/forgetpassword'